### ISSUE TITLE
[Bug]: Getting a JAR not found issue when I ran a simple salesforce example

### ISSUE THREAD

**Issue by BuddhiWathsala** [ballerina-platform/ballerina-extended-library#230]
### Connector Name

module/salesforce (Salesforce)

### What happened?

When I ran a simple salesforce example, it gave me the following error.

```
[2022-01-06 16:10:39,247] SEVERE {b7a.log.crash} - Cannot find the generated jar library for module: salesforce.soap 
java.lang.IllegalStateException: Cannot find the generated jar library for module: salesforce.soap
        at io.ballerina.projects.JBallerinaBackend.lambda$codeGeneratedLibrary$3(JBallerinaBackend.java:502)
        at java.base/java.util.Optional.orElseThrow(Optional.java:408)
        at io.ballerina.projects.JBallerinaBackend.codeGeneratedLibrary(JBallerinaBackend.java:501)
        at io.ballerina.projects.JBallerinaBackend.codeGeneratedLibrary(JBallerinaBackend.java:274)
        at io.ballerina.projects.JarResolver.addCodeGeneratedLibraryPaths(JarResolver.java:122)
        at io.ballerina.projects.JarResolver.lambda$getJarFilePathsRequiredForExecution$3(JarResolver.java:81)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
        at io.ballerina.projects.JarResolver.getJarFilePathsRequiredForExecution(JarResolver.java:79)
        at io.ballerina.cli.task.RunExecutableTask.getAllClassPaths(RunExecutableTask.java:117)
        at io.ballerina.cli.task.RunExecutableTask.runGeneratedExecutable(RunExecutableTask.java:96)
        at io.ballerina.cli.task.RunExecutableTask.execute(RunExecutableTask.java:76)
        at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
        at io.ballerina.cli.cmd.RunCommand.execute(RunCommand.java:203)
        at java.base/java.util.Optional.ifPresent(Optional.java:183)
        at io.ballerina.cli.launcher.Main.main(Main.java:51)
```

- Salesforce version: 4.0.0
- Ballerina version Swan Lake Beta 6

I ran [this example](https://github.com/ballerina-platform/module-ballerinax-sfdc/blob/4f7089571310042ba8a3f17cc46fb5e08ba93910/salesforce/modules/bulk/tests/bulk_csv_insert.bal#L459) in a separate Ballerina project.

**Comment by sachinira** [comment]
@BuddhiWathsala I executed a same sample creating a separate Ballerina project and the sample was working fine. The specifications I used in my local environment are
- Salesforce version: 4.0.0
- Ballerina version Swan Lake Beta 6
- Ubuntu 20.04 LTS
- Java 11

This specific sample only uses `salesforce.bulk` client in it. This kind of log is not possible in that scenario too because it shows a log crash in `salesforce.soap` module. Please verify and update if the same issue still persists.

**Comment by BuddhiWathsala** [comment]
Tested it after cleaning my Ballerina cache and now it works fine. Hence, closing the issue.
