### ISSUE TITLE
[Bug]: Concatenated strings as inputs does not work in Salesforce connector 

### ISSUE THREAD

**Issue by abeykoon** [ballerina-platform/ballerina-extended-library#92]
### Connector Name

module/salesforce (Salesforce)

### What happened?

When a user uses a string that is concatenated with + as the query in 'getQueryResults' operation in the salesforce connector, he gets the following error.

Ex - getQueryResult("string one"+"String two"+
"string three");

Please refer to log output.

When he uses string templates to keep the multiple lines, the issue is solved. It would be great if we can improve the error message shown.

Note - This is a feedback received from an internal user

### Relevant log output

```shell
- Cannot find the generated jar library for module: sfdc
java.lang.IllegalStateException: Cannot find the generated jar library for module: sfdc
at io.ballerina.projects.JBallerinaBackend.lambda$codeGeneratedLibrary$4(JBallerinaBackend.java:475)
at java.base/java.util.Optional.orElseThrow(Optional.java:408)
at io.ballerina.projects.JBallerinaBackend.codeGeneratedLibrary(JBallerinaBackend.java:474)
at io.ballerina.projects.JBallerinaBackend.codeGeneratedLibrary(JBallerinaBackend.java:251)
at io.ballerina.projects.JarResolver.addCodeGeneratedLibraryPaths(JarResolver.java:91)
at io.ballerina.projects.JarResolver.lambda$getJarFilePathsRequiredForExecution$3(JarResolver.java:73)
at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1654)
at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
at io.ballerina.projects.JarResolver.getJarFilePathsRequiredForExecution(JarResolver.java:71)
at io.ballerina.projects.JBallerinaBackend.emitExecutable(JBallerinaBackend.java:481)
at io.ballerina.projects.JBallerinaBackend.emit(JBallerinaBackend.java:175)
at io.ballerina.cli.task.CreateExecutableTask.execute(CreateExecutableTask.java:101)
at io.ballerina.cli.TaskExecutor.executeTasks(TaskExecutor.java:40)
at io.ballerina.cli.cmd.BuildCommand.execute(BuildCommand.java:272)
at java.base/java.util.Optional.ifPresent(Optional.java:183)
at io.ballerina.cli.launcher.Main.main(Main.java:58)
make: *** [Makefile:7: project/target/bin/*.jar] Error 1
```

**Comment by sachinira** [comment]
- This issue is tested on the following code sample  on Salesforce connector. Operation is working fine.
```ballerina
import ballerina/log;
import ballerinax/sfdc;

public function main(){

    // Create Salesforce client configuration by reading from config file.
    sfdc:SalesforceConfiguration sfConfig = {
        baseUrl: "<BASE_URL>",
        clientConfig: {
            clientId: "<CLIENT_ID>",
            clientSecret: "<CLIENT_SECRET>",
            refreshToken: "<REFESH_TOKEN>",
            refreshUrl: "<REFRESH_URL>"
        }
    };

    // Create Salesforce client.
    sfdc:Client baseClient = checkpanic new(sfConfig);
    
    int totalRecords = 0;

    sfdc:SoqlResult|sfdc:Error res = baseClient->getQueryResult("SELECT" + " name FROM Account");

    if (res is sfdc:SoqlResult) {
        if (res.totalSize > 0){
            totalRecords = res.records.length() ;
            string|error nextRecordsUrl = res["nextRecordsUrl"].toString();
            while (nextRecordsUrl is string && nextRecordsUrl.trim() != "") {
                log:printInfo("Found new query result set! nextRecordsUrl:" + nextRecordsUrl);
                sfdc:SoqlResult|sfdc:Error nextRes = baseClient->getNextQueryResult(<@untainted>nextRecordsUrl);
                
                if (nextRes is sfdc:SoqlResult) {
                    totalRecords = totalRecords + nextRes.records.length();
                    res = nextRes;
                } 
            }
            log:printInfo(totalRecords.toString() + " Records Recieved");
        }
        else{
            log:printInfo("No Results Found");
        }
        
    } else {
        log:printError(msg = res.message());
    }

}
```
**Result**
![Screenshot from 2021-10-11 10-28-37](https://user-images.githubusercontent.com/34184297/136735496-98a058d4-c780-4fd0-b1c4-41d2ea26e404.png)

- Tested on choreo prod, staging and dev and the operation is working fine for the following sample

![Screenshot from 2021-10-11 10-03-59](https://user-images.githubusercontent.com/34184297/136736010-7419a42f-f990-4977-9504-c8c5458c0e34.png)

**Result**
![Screenshot from 2021-10-11 10-04-44](https://user-images.githubusercontent.com/34184297/136735557-1e28096f-5667-4f12-b472-673e3c4bda37.png)
